### ISSUE TITLE
login/crypt vulnerabilites 

### ISSUE THREAD

**Issue by ghost** [rthornton128/login#5]
The login/crypt package is vulnerable to brute force attacks, timing attacks and probably more. Use [bcrypt](http://godoc.org/golang.org/x/crypto/bcrypt), [scrypt](http://godoc.org/golang.org/x/crypto/scrypt) or some other package written by a crypto expert.  To avoid timing attacks, compare hashes with [subtle.ConstantTimeCompare](http://godoc.org/crypto/subtle#ConstantTimeCompare). Do not use bytes.Compare.

**Comment by rthornton128** [comment]
In login/crypt I state in the package doc that bcrypt would be better but chose to use this method for the example. I really appreciate the heads up on subtle.ConstantTimeCompare. I was not aware of it.

**Comment by ghost** [comment]
You should clearly state that the package is dangerous to use with real user data.  Stating that bcrypt is a better choice does not convey the danger involved.

It's easy to do this right.
