### ISSUE TITLE
login.go html escaping is unconventional

### ISSUE THREAD

**Issue by ghost** [rthornton128/login#6]
The code in login.go calls html.EscapeString on all form values ([example](https://github.com/rthornton128/login/blob/5fea8fd3bb37db91361d5500341e15431af992d1/login.go#L41)).  I am unsure if this to ensure that later output is properly escaped or some other reason.

Web applications typically do not escape data on input, but instead escape data just before output. You can get output escaping for free by switching from text/template to [html/template](http://godoc.org/html/template).

Specific recommendation: remove all uses of html.EscapeString in login.go. Switch from text/template to html/template.

Edit: [Here's another one](https://github.com/rthornton128/login/blob/5fea8fd3bb37db91361d5500341e15431af992d1/middle/middle.go#L16).  Do this instead:

			log.Printf("Attempted login by: %q (%s)", r.FormValue("UserID"), r.RemoteAddr)

The %q format verb will escape control chars and anything else that might cause issues in your log files.

**Comment by rthornton128** [comment]
I meant to use html/template but goimports changed it on me. 

I will remove the html.EscapeString from the input then. I believe I've done the SQL queries correctly to protect against SQL injection attacks.

**Comment by ghost** [comment]
Protect against SQL attacks by using SQL escaping, not HTML escaping. The database drivers can handle the escaping for you.
